# Generated by Django 5.0.5 on 2024-05-08 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_experiment_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experiment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Experiment Scheduled On"
                    ),
                ),
                (
                    "report_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Report Due On"
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.experiment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Experiment",
                "verbose_name_plural": "User Experiments",
                "unique_together": {("student", "experiment")},
            },
        ),
    ]
