# Generated by Django 5.0.5 on 2024-05-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_userexperiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexperiment",
            name="Semester",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.semester",
            ),
        ),
        migrations.AddField(
            model_name="userexperiment",
            name="report",
            field=models.FileField(
                blank=True, null=True, upload_to="reports/", verbose_name="Report"
            ),
        ),
        migrations.AddField(
            model_name="userexperiment",
            name="submission_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Report Submitted On"
            ),
        ),
    ]
