# Generated by Django 5.0.5 on 2024-05-09 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_userexperiment_semester_userexperiment_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexperiment",
            name="Semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.semester"
            ),
        ),
    ]
