# Generated by Django 5.0.5 on 2024-05-09 16:54

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_semester_userexperiment_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexperiment",
            name="report",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=main.models.upload_report_location,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf"], message="Please upload a .pdf file."
                    )
                ],
                verbose_name="Report",
            ),
        ),
    ]
