# Generated by Django 5.0.5 on 2024-05-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_userexperiment_experiment_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userexperiment",
            unique_together={("student", "experiment", "semester")},
        ),
    ]
