# Generated by Django 5.0.5 on 2024-05-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_userexperiment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userexperiment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
