# Generated by Django 5.0.5 on 2024-05-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_userexperiment_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexperiment",
            old_name="id",
            new_name="uid",
        ),
    ]
