# Generated by Django 5.0.5 on 2024-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="G1",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField(unique=True, verbose_name="ID")),
            ],
        ),
    ]
