# Generated by Django 5.0.5 on 2024-05-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0002_g1data_delete_g1"),
        ("main", "0011_alter_userexperiment_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="g1data",
            name="id",
            field=models.PositiveIntegerField(unique=True, verbose_name="data point #"),
        ),
        migrations.AlterUniqueTogether(
            name="g1data",
            unique_together={("userexperiment", "id")},
        ),
    ]
