# Generated by Django 5.0.5 on 2024-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0003_alter_g1data_id_alter_g1data_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="g1data",
            name="Remarks",
            field=models.TextField(blank=True, default="", verbose_name="Remarks"),
        ),
        migrations.AddField(
            model_name="g1data",
            name="file",
            field=models.FileField(
                blank=True, upload_to="G1/", verbose_name="Data File"
            ),
        ),
        migrations.AddField(
            model_name="g1data",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
        ),
    ]
