# Generated by Django 5.0.5 on 2024-05-09 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0004_g1data_remarks_g1data_file_g1data_metadata"),
        ("main", "0011_alter_userexperiment_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="G1",
            fields=[
                (
                    "experiment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="main.experiment",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
            ],
            bases=("main.experiment",),
        ),
    ]
