# Generated by Django 5.0.5 on 2024-05-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0005_g1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
            ],
            options={
                "verbose_name": "Metadata",
                "verbose_name_plural": "Metadata",
            },
        ),
        migrations.DeleteModel(
            name="G1",
        ),
    ]
