# Generated by Django 5.0.5 on 2024-05-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0006_metadata_delete_g1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Metadata",
            new_name="G1Metadata",
        ),
        migrations.AlterModelOptions(
            name="g1metadata",
            options={
                "verbose_name": "G1 Metadata",
                "verbose_name_plural": "G1 Metadata",
            },
        ),
    ]
