# Generated by Django 5.0.5 on 2024-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0008_delete_g1metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="G1Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(blank=True, default=dict, verbose_name="Fields"),
                ),
                (
                    "additional_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Fields"
                    ),
                ),
            ],
            options={
                "verbose_name": "G1 Metadata",
                "verbose_name_plural": "G1 Metadata",
            },
        ),
    ]
