# Generated by Django 5.0.5 on 2024-05-10 21:12

import G1.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0009_g1metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="g1metadata",
            name="template",
            field=models.FileField(
                blank=True,
                upload_to=G1.utils.upload_G1template,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["xlsx", "xls", "csv"],
                        message="Please upload a valid file format (.xlsx, .xls, .csv)",
                    )
                ],
                verbose_name="Template",
            ),
        ),
        migrations.AlterField(
            model_name="g1data",
            name="file",
            field=models.FileField(
                blank=True, upload_to=G1.utils.upload_G1data, verbose_name="Data File"
            ),
        ),
        migrations.AlterField(
            model_name="g1data",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
        ),
    ]
