# Generated by Django 5.0.5 on 2024-05-11 01:38

import G1.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0010_g1metadata_template_alter_g1data_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="g1data",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=G1.utils.upload_G1data,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["xlsx", "xls"],
                        message="Please upload a valid file format (.xlsx, .xls)",
                    )
                ],
                verbose_name="Data File",
            ),
        ),
        migrations.AlterField(
            model_name="g1metadata",
            name="template",
            field=models.FileField(
                blank=True,
                upload_to=G1.utils.upload_G1template,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["xlsx", "xls"],
                        message="Please upload a valid file format (.xlsx, .xls)",
                    )
                ],
                verbose_name="Template",
            ),
        ),
    ]
