# Generated by Django 5.0.5 on 2024-05-21 17:43

import G1.utils
import G1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0011_alter_g1data_file_alter_g1metadata_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="g1data",
            options={
                "ordering": ["id"],
                "verbose_name": "G1 Data",
                "verbose_name_plural": "G1 Data",
            },
        ),
        migrations.RemoveField(
            model_name="g1data",
            name="Remarks",
        ),
        migrations.RemoveField(
            model_name="g1data",
            name="metadata",
        ),
        migrations.AddField(
            model_name="g1data",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="g1data",
            name="proc_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Processed Data"
            ),
        ),
        migrations.AddField(
            model_name="g1data",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Raw Data"),
        ),
        migrations.AlterField(
            model_name="g1data",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=G1.utils.upload_G1data,
                validators=[G1.validators.validate_file_extension],
                verbose_name="Data File",
            ),
        ),
        migrations.AlterField(
            model_name="g1data",
            name="uid",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="g1metadata",
            name="template",
            field=models.FileField(
                blank=True,
                upload_to=G1.utils.upload_G1template,
                validators=[G1.validators.validate_file_extension],
                verbose_name="Template File",
            ),
        ),
    ]
