# Generated by Django 5.0.5 on 2024-05-22 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0012_alter_g1data_options_remove_g1data_remarks_and_more"),
        ("main", "0013_rename_id_userexperiment_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="G1Results",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "rate_dicts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Rate Dictionaries"
                    ),
                ),
                (
                    "ea_dicts",
                    models.JSONField(blank=True, default=list, verbose_name="Ea Dicts"),
                ),
                (
                    "ro_base_dicts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="RO Base Dicts"
                    ),
                ),
                (
                    "ro_ester_dicts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="RO Ester Dicts"
                    ),
                ),
                (
                    "userexperiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "G1 Results",
                "verbose_name_plural": "G1 Results",
            },
        ),
    ]
