# Generated by Django 5.0.5 on 2024-05-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0014_alter_g1results_ea_dicts_alter_g1results_rate_dicts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="g1results",
            name="ea_dicts",
            field=models.JSONField(blank=True, default=list, verbose_name="Ea Dicts"),
        ),
        migrations.AlterField(
            model_name="g1results",
            name="rate_dicts",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rate Dictionaries"
            ),
        ),
        migrations.AlterField(
            model_name="g1results",
            name="ro_base_dicts",
            field=models.JSONField(
                blank=True, default=list, verbose_name="RO Base Dicts"
            ),
        ),
        migrations.AlterField(
            model_name="g1results",
            name="ro_ester_dicts",
            field=models.JSONField(
                blank=True, default=list, verbose_name="RO Ester Dicts"
            ),
        ),
    ]
