# Generated by Django 5.0.5 on 2024-05-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G1", "0015_alter_g1results_ea_dicts_alter_g1results_rate_dicts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="g1results",
            name="rate_dicts",
        ),
        migrations.AddField(
            model_name="g1data",
            name="is_processed",
            field=models.BooleanField(default=False, verbose_name="Processed"),
        ),
    ]
