# Generated by Django 5.0.5 on 2024-05-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="g3metadata",
            name="fields",
        ),
    ]
