# Generated by Django 5.0.5 on 2024-05-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0002_remove_g3metadata_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="g3metadata",
            name="fields",
            field=models.JSONField(blank=True, default=dict, verbose_name="Fields"),
        ),
    ]
