# Generated by Django 5.0.5 on 2024-05-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0003_g3metadata_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="g3metadata",
            options={
                "ordering": ["id"],
                "verbose_name": "G3 Metadata",
                "verbose_name_plural": "G3 Metadata",
            },
        ),
    ]
