# Generated by Django 5.0.5 on 2024-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0005_alter_g3data_options_alter_g3metadata_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="G3SimulMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_fields",
                    models.JSONField(blank=True, default=dict, verbose_name="Fields"),
                ),
                (
                    "output_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Additional Fields"
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Simul Metadata",
                "verbose_name_plural": "G3 Simul Metadata",
            },
        ),
    ]
