# Generated by Django 5.0.5 on 2024-05-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0006_g3simulmetadata"),
        ("main", "0011_alter_userexperiment_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="G3SimulData",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parameters"
                    ),
                ),
                (
                    "results",
                    models.JSONField(blank=True, default=dict, verbose_name="Results"),
                ),
                (
                    "userexperiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Simul Data",
                "verbose_name_plural": "G3 Simul Data",
            },
        ),
    ]
