# Generated by Django 5.0.5 on 2024-05-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0008_g3simulmetadata_parameters_g3simulmetadata_results_and_more"),
        ("main", "0011_alter_userexperiment_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="G3SimulData",
            new_name="G3SimulParams",
        ),
    ]
