# Generated by Django 5.0.5 on 2024-05-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0009_rename_g3simuldata_g3simulparams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="g3simulmetadata",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="g3simulmetadata",
            name="results",
        ),
        migrations.DeleteModel(
            name="G3SimulParams",
        ),
    ]
