# Generated by Django 5.0.5 on 2024-05-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0010_remove_g3simulmetadata_parameters_and_more"),
        ("main", "0011_alter_userexperiment_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="G3SimulGlobalParams",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Global Parameters"
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Simul Global Params",
                "verbose_name_plural": "G3 Simul Global Params",
            },
        ),
        migrations.CreateModel(
            name="G3SimulParams",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Parameters"
                    ),
                ),
                (
                    "userexperiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Simul Data",
                "verbose_name_plural": "G3 Simul Data",
            },
        ),
    ]
