# Generated by Django 5.0.5 on 2024-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0011_g3simulglobalparams_g3simulparams"),
    ]

    operations = [
        migrations.AddField(
            model_name="g3data",
            name="processed_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Processed Data"
            ),
        ),
    ]
