# Generated by Django 5.0.5 on 2024-05-14 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0012_g3data_processed_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="g3simulparams",
            options={
                "verbose_name": "G3 Simul Params",
                "verbose_name_plural": "G3 Simul Params",
            },
        ),
    ]
