# Generated by Django 5.0.5 on 2024-05-15 22:07

import G3.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0013_alter_g3simulparams_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="g3data",
            old_name="metadata",
            new_name="data",
        ),
        migrations.AlterField(
            model_name="g3metadata",
            name="template",
            field=models.FileField(
                blank=True,
                upload_to=G3.utils.upload_G3template,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["csv", "txt"],
                        message="Please upload a valid file format (.csv or .txt)",
                    )
                ],
                verbose_name="Template",
            ),
        ),
    ]
