# Generated by Django 5.0.5 on 2024-05-15 22:27

import G3.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0014_rename_metadata_g3data_data_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="g3data",
            old_name="processed_data",
            new_name="proc_data",
        ),
        migrations.RemoveField(
            model_name="g3data",
            name="data",
        ),
        migrations.AddField(
            model_name="g3data",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="g3data",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, verbose_name="Raw Data"),
        ),
        migrations.AlterField(
            model_name="g3data",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=G3.utils.upload_G3data,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["csv", "txt"],
                        message="Please upload a valid file format (.csv or .txt)",
                    )
                ],
                verbose_name="Data File",
            ),
        ),
    ]
