# Generated by Django 5.0.5 on 2024-05-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0015_rename_processed_data_g3data_proc_data_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="G3SimulMetadata",
        ),
    ]
