# Generated by Django 5.0.5 on 2024-05-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0016_delete_g3simulmetadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="g3simulparams",
            old_name="uid",
            new_name="id",
        ),
    ]
