# Generated by Django 5.0.5 on 2024-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0017_rename_uid_g3simulparams_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="g3simulparams",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
