# Generated by Django 5.0.5 on 2024-05-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0018_alter_g3simulparams_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="g3simulparams",
            old_name="id",
            new_name="uid",
        ),
    ]
