# Generated by Django 5.0.5 on 2024-05-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0019_rename_id_g3simulparams_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="g3simulparams",
            old_name="parameters",
            new_name="params",
        ),
    ]
