# Generated by Django 5.0.5 on 2024-05-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0020_rename_parameters_g3simulparams_params"),
    ]

    operations = [
        migrations.DeleteModel(
            name="G3SimulGlobalParams",
        ),
    ]
