# Generated by Django 5.0.5 on 2024-05-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0021_delete_g3simulglobalparams"),
    ]

    operations = [
        migrations.CreateModel(
            name="G3SimulGlobalParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Global Parameters"
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Simul Global Params",
                "verbose_name_plural": "G3 Simul Global Params",
            },
        ),
    ]
