# Generated by Django 5.0.5 on 2024-05-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0022_g3simulglobalparams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="g3data",
            name="Remarks",
        ),
    ]
