# Generated by Django 5.0.5 on 2024-05-16 18:55

import G3.utils
import G3.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0023_remove_g3data_remarks"),
        ("main", "0013_rename_id_userexperiment_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="g3data",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=G3.utils.upload_G3data,
                validators=[G3.validators.validate_file_extension],
                verbose_name="Data File",
            ),
        ),
        migrations.AlterField(
            model_name="g3metadata",
            name="template",
            field=models.FileField(
                blank=True,
                upload_to=G3.utils.upload_G3template,
                validators=[G3.validators.validate_file_extension],
                verbose_name="Template",
            ),
        ),
        migrations.CreateModel(
            name="G3AnalyzedData",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "analyzed_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Analyzed Data"
                    ),
                ),
                (
                    "userexperiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Analysis",
                "verbose_name_plural": "G3 Analysis",
            },
        ),
    ]
