# Generated by Django 5.0.5 on 2024-05-16 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0024_alter_g3data_file_alter_g3metadata_template_and_more"),
        ("main", "0013_rename_id_userexperiment_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="g3data",
            name="is_simulated",
            field=models.BooleanField(default=False, verbose_name="Simulated"),
        ),
        migrations.CreateModel(
            name="G3AnalysisResults",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "grouped_dicts",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Grouped Dictionaries"
                    ),
                ),
                (
                    "results",
                    models.JSONField(blank=True, default=dict, verbose_name="Results"),
                ),
                (
                    "userexperiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Analysis Results",
                "verbose_name_plural": "G3 Analysis Results",
            },
        ),
        migrations.DeleteModel(
            name="G3AnalyzedData",
        ),
    ]
