# Generated by Django 5.0.5 on 2024-05-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0025_g3data_is_simulated_g3analysisresults_and_more"),
        ("main", "0013_rename_id_userexperiment_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="G3Results",
            fields=[
                ("uid", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dat_grp_o1",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data Groups (Order 1)"
                    ),
                ),
                (
                    "dat_grp_o2",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data Groups (Order 2)"
                    ),
                ),
                (
                    "dat_grp_o3",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data Groups (Order 3)"
                    ),
                ),
                (
                    "results",
                    models.JSONField(blank=True, default=dict, verbose_name="Results"),
                ),
                (
                    "userexperiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.userexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "G3 Results",
                "verbose_name_plural": "G3 Results",
            },
        ),
        migrations.DeleteModel(
            name="G3AnalysisResults",
        ),
    ]
