# Generated by Django 5.0.5 on 2024-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("G3", "0027_rename_dat_grp_o2_g3results_ea_dicts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="g3results",
            name="ea_dicts",
        ),
        migrations.RemoveField(
            model_name="g3results",
            name="rate_dicts",
        ),
        migrations.RemoveField(
            model_name="g3results",
            name="results",
        ),
        migrations.RemoveField(
            model_name="g3results",
            name="ro_dicts",
        ),
        migrations.AddField(
            model_name="g3results",
            name="ea_dataset",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ea Dictionaries"
            ),
        ),
        migrations.AddField(
            model_name="g3results",
            name="rate_dataset",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rate Dictionaries"
            ),
        ),
        migrations.AddField(
            model_name="g3results",
            name="ro_dataset",
            field=models.JSONField(
                blank=True, default=list, verbose_name="RO Dictionaries"
            ),
        ),
    ]
