"""
Django settings for rdm4lab project.

Generated by 'django-admin startproject' using Django 5.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from '.env' file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",  # Humanize numbers
    "main.apps.MainConfig",  # Main app configuration
    "G1.apps.G1Config",  # G1 app configuration
    "G3.apps.G3Config",  # G3 app configuration
    "crispy_forms",  # crispy forms
    "crispy_bootstrap5",  # crispy bootstrap5 template pack
    "ckeditor",  # ckeditor for rich text editing
    "ckeditor_uploader",  # ckeditor file uploader
    "django_json_widget",  # json widget
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rdm4lab.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # Global templates directory
        "APP_DIRS": True,  # Enable app level templates
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.current_semester",  # get current semester
            ],
        },
    },
]

WSGI_APPLICATION = "rdm4lab.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# PostgreSQL database configuration
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # database engine
        "NAME": os.getenv("DATABASE_NAME"),  # PostgreSQL database name
        "USER": os.getenv("DATABASE_USER"),  # PostgreSQL username
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),  # PostgreSQL password
        "HOST": "localhost",  # Set to empty string for localhost
        "PORT": "5432",  # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Use the custom user model for authentication
AUTH_USER_MODEL = "main.User"


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"  # Default language code

TIME_ZONE = "CET"  # Default time zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"

# This is a list of filesystem directories to check when loading static files.
# It is useful for development, but in production, you typically collect
# static files into a single directory using the collectstatic command.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Global static files directory
]

# This setting defines the folder path where all static files
# will be collected to, when you run collectstatic.
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Crispy forms settings
CRISPY_ALLOWED_TEMPLATE_PACKS = ["bootstrap5"]  # Allowed template packs
CRISPY_TEMPLATE_PACK = "bootstrap5"  # Default template pack

LOGIN_REDIRECT_URL = "/home"  # URL to redirect to after a successful login
LOGOUT_REDIRECT_URL = "/home"  # URL to redirect to after a successful logout

# Media files settings
MEDIA_URL = "/media/"  # URL to serve media files
MEDIA_ROOT = os.path.join(BASE_DIR, "media")  # Path to the media directory

# CKEditor settings
CKEDITOR_UPLOAD_PATH = (
    "uploads/ckeditor/"  # CKEditor upload path relative to MEDIA_ROOT
)
CKEDITOR_IMAGE_BACKEND = "pillow"  # Image processing backend
CKEDITOR_CONFIGS = {
    "default": {
        # Toolbar configuration
        # name - Toolbar name
        # items - The buttons enabled in the toolbar
        "toolbar_DefaultToolbarConfig": [
            {
                "name": "basicstyles",
                "items": [
                    "Bold",
                    "Italic",
                    "Underline",
                    "Strike",
                    "Subscript",
                    "Superscript",
                ],
            },
            {
                "name": "clipboard",
                "items": [
                    "Undo",
                    "Redo",
                ],
            },
            {
                "name": "paragraph",
                "items": [
                    "NumberedList",
                    "BulletedList",
                    "Outdent",
                    "Indent",
                    "HorizontalRule",
                    "JustifyLeft",
                    "JustifyCenter",
                    "JustifyRight",
                    "JustifyBlock",
                ],
            },
            {
                "name": "format",
                "items": [
                    "Format",
                ],
            },
            {
                "name": "extra",
                "items": [
                    "Link",
                    "Unlink",
                    "Blockquote",
                    "Image",
                    "Table",
                    "CodeSnippet",
                    "Mathjax",
                    "Embed",
                ],
            },
            {
                "name": "source",
                "items": [
                    "Maximize",
                    "Source",
                ],
            },
        ],
        # This hides the default title provided by CKEditor
        "title": False,
        # Use this toolbar
        "toolbar": "DefaultToolbarConfig",
        # Which tags to allow in format tab
        "format_tags": "p;h1;h2;h3;h4;h5;h6;pre;address;div",
        # Remove these dialog tabs (semicolon separated dialog:tab)
        "removeDialogTabs": ";".join(
            [
                "image:advanced",
                "image:Link",
                "link:upload",
                "table:advanced",
                "tableProperties:advanced",
            ]
        ),
        "linkShowTargetTab": False,
        "linkShowAdvancedTab": False,
        # CKEditor height and width settings
        "height": "250px",
        "width": "auto",
        "forcePasteAsPlainText ": True,
        # Class used inside span to render mathematical formulae using latex
        "mathJaxClass": "mathjax-latex",
        # Mathjax library link to be used to render mathematical formulae
        "mathJaxLib": "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_SVG",
        # Tab = 4 spaces inside the editor
        "tabSpaces": 4,
        # Extra plugins to be used in the editor
        "extraPlugins": ",".join(
            [
                # 'devtools',  # Shows a tooltip in dialog boxes for developers
                "mathjax",  # Used to render mathematical formulae
                "codesnippet",  # Used to add code snippets
                "image2",  # Loads new and better image dialog
                "embed",  # Used for embedding media (YouTube/Slideshare etc)
                "tableresize",  # Used to allow resizing of columns in tables
            ]
        ),
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(message)s",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
    },
    "handlers": {
        "G3_logfile": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/G3.log"),
            "formatter": "verbose",
        },
        "G1_logfile": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs/G1.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "G3": {
            "handlers": ["G3_logfile"],
            "level": "DEBUG",
            "propagate": False,
        },
        "G1": {
            "handlers": ["G1_logfile"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
